/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package urbanstew.RehearsalAssistant;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int annotation_list=0x7f050005;
        public static final int button=0x7f050006;
        public static final int create=0x7f050004;
        public static final int help=0x7f050002;
        public static final int name=0x7f050003;
        public static final int new_run=0x7f050001;
        public static final int run_list=0x7f050000;
    }
    public static final class layout {
        public static final int annotationslist_item=0x7f030000;
        public static final int main=0x7f030001;
        public static final int new_run=0x7f030002;
        public static final int playback=0x7f030003;
        public static final int record=0x7f030004;
        public static final int runslist_item=0x7f030005;
    }
    public static final class string {
        public static final int about=0x7f040000;
        public static final int app_name=0x7f040001;
        public static final int instructions=0x7f040002;
    }
}
